---
- hosts: all
  vars:
  - one: "{{param1|default('bad1')}}"
  - two: "{{param2|default('bad2')}}"
  - three: "{{param3|default('bad3')}}"

  tasks:
  - name: Print Vars
    debug: msg="param1 is {{ one }}, param2 is {{two}}, param3 is {{three}}"
    
  - name: Print EnvVars
      shell: printenv
      register: ps
        debug: var=ps.stdout_lines
